'use strict';
// Staff tokens live only in memory. Reloading or closing this tab signs out.
const $ = s => document.querySelector(s), root = $('#root'), dialog = $('#editor');
const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const money = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(value || 0));
const date = value => value ? new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'}) : '—';
const badge = value => `<span class="badge ${['confirmed','delivered','paid','live','sent'].includes(value)?'good':['cancelled','failed','disabled'].includes(value)?'bad':'warn'}">${esc(String(value).replaceAll('_',' '))}</span>`;
let token = '', actor = null, section = 'dashboard', page = 1, records = [], timer, saving = false, formHandler, lastAlert = null, filter = {}, viewVersion = 0;
function toast(message){ $('#toast').textContent=message; $('#toast').classList.add('visible'); setTimeout(()=>$('#toast').classList.remove('visible'),6000); }
async function api(path,method='GET',data){
  const response = await fetch('/api/v1'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(data!==undefined?{body:JSON.stringify(data)}:{})});
  const value = response.status===204?null:await response.json();
  if(!response.ok){
    if(response.status===401 && token){ token=''; actor=null; clearInterval(timer); dialog.close(); login('Your session expired. Sign in again.'); }
    throw new Error([value?.message,...Object.values(value?.fields||{})].filter(Boolean).join(' '));
  }
  return value;
}
const input = (key,label,value='',type='text',required=true) => `<label>${esc(label)}<input name="${esc(key)}" type="${type}" value="${esc(value)}" ${required?'required':''} ${type==='number'?'min="0" step="0.01"':''}></label>`;
const check = (key,label,value=false) => `<label class="check"><input name="${esc(key)}" type="checkbox" ${value?'checked':''}>${esc(label)}</label>`;
const select = (key,label,value,options) => `<label>${esc(label)}<select name="${esc(key)}">${options.map(option=>`<option value="${esc(option)}" ${option===value?'selected':''}>${esc(option.replaceAll('_',' '))}</option>`).join('')}</select></label>`;
const textarea = (key,label,value='',required=false) => `<label class="full">${esc(label)}<textarea name="${esc(key)}" ${required?'required':''}>${esc(value)}</textarea></label>`;
function formData(form){ const result=Object.fromEntries(new FormData(form)); form.querySelectorAll('input[type=checkbox]').forEach(el=>result[el.name]=el.checked); return result; }
function editor(title,html,handler){ formHandler=handler; $('#editor-title').textContent=title; $('#editor-body').innerHTML=html; $('#editor-error').textContent=''; dialog.showModal(); }
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>dialog.close());
$('#editor-form').onsubmit=async event=>{ event.preventDefault(); if(saving)return; saving=true; const button=event.submitter; button.disabled=true; $('#editor-error').textContent=''; try{await formHandler(formData(event.target)); dialog.close(); toast('Changes saved'); await render();}catch(error){$('#editor-error').textContent=error.message;}finally{saving=false;button.disabled=false;} };
function login(message=''){
  root.innerHTML=`<main class="login"><form class="panel" id="login"><div class="brand">grove & stone / owners</div><h1>Welcome back</h1><p class="muted">Manage orders, stock and deliveries.</p>${input('email','Work email','','email')}${input('password','Password','','password')}<p id="login-error" role="alert">${esc(message)}</p><button class="primary">Sign in securely</button><p class="muted small external">Staff access only. Ask the owner to create your account. Sessions expire after 15 minutes.</p><a class="external small" href="https://grove-and-stone-web.onrender.com/">Return to the shop</a></form></main>`;
  $('#login [name=email]').autocomplete='username'; $('#login [name=password]').autocomplete='current-password';
  $('#login').onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{const result=await api('/admin/auth/login','POST',formData(event.target));token=result.access_token;actor=result.admin;lastAlert=null;shell();await render();poll();timer=setInterval(poll,15000);}catch(error){$('#login-error').textContent=error.message;}finally{button.disabled=false;}};
}
const sections={dashboard:'Overview',orders:'Orders',inventory:'Inventory',alerts:'Order alerts',products:'Products',delivery:'Delivery areas',postal:'Postal directory',banners:'Home offers',seasons:'Mango seasons',refunds:'Refunds',settings:'Business setup',staff:'Team',audit:'Activity log'};
function shell(){
  section='dashboard';page=1;filter={};
  root.innerHTML=`<aside class="sidebar"><div><div class="brand">grove & stone</div><span class="small muted">OWNER WORKSPACE</span></div><nav aria-label="Owner navigation">${Object.entries(sections).filter(([key])=>actor.role==='admin'||['dashboard','orders','inventory','alerts'].includes(key)).map(([key,label])=>`<button data-section="${key}">${label}</button>`).join('')}</nav><div class="bottom"><div><strong>${esc(actor.name)}</strong><div class="small muted">${esc(actor.role)}</div></div><button id="logout">Sign out</button></div></aside><main class="workspace"><div id="content"></div></main>`;
  root.querySelectorAll('[data-section]').forEach(button=>button.onclick=()=>{section=button.dataset.section;page=1;filter={};render();});
  $('#logout').onclick=async()=>{try{await api('/admin/auth/logout','POST',{});}finally{token='';actor=null;clearInterval(timer);login();}};
}
async function poll(){
  if(!token||document.hidden)return;
  try{const data=await api('/admin/alerts?page_size=1');const newest=data.items[0]?.id;
    if(lastAlert!==null && newest && newest!==lastAlert){toast(`New order activity. ${data.unread} unread alerts.`);if('Notification'in window&&Notification.permission==='granted')new Notification('Grove & Stone order update',{body:'Open the owner dashboard to review the new activity.'});if(['dashboard','alerts','orders'].includes(section)&&!dialog.open)await render();}
    lastAlert=newest||'';const button=$('[data-section="alerts"]');if(button)button.textContent=`Order alerts${data.unread?' · '+data.unread:''}`;
  }catch(error){if(token)toast('Order updates could not refresh. '+error.message);}
}
function table(headers,rows){return `<div class="tablewrap"><table><thead><tr>${headers.map(text=>`<th>${esc(text)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}" class="empty">No records to show.</td></tr>`}</tbody></table></div>`;}
const cell = (value,wrap=false)=>`<td${wrap?' class="wrap"':''}>${value}</td>`;
const action = (name,id,label)=>`<button type="button" data-action="${name}" data-id="${esc(id)}">${esc(label)}</button>`;
const pager = data => data.total===undefined?'':`<div class="pager"><span class="muted small">${data.total} records · Page ${page} of ${Math.max(1,Math.ceil(data.total/data.page_size))}</span><button data-page="-1" ${page===1?'disabled':''}>Previous</button><button data-page="1" ${page*data.page_size>=data.total?'disabled':''}>Next</button></div>`;
const query = () => new URLSearchParams({page:String(page),page_size:'20',...Object.fromEntries(Object.entries(filter).filter(([,v])=>v!==''))}).toString();
const orderTable = rows=>table(['Order','Placed (IST)','Status','Payment','Delivery','Total',''],rows.map(o=>`<tr>${cell(`<strong>${esc(o.order_number)}</strong>`)}${cell(date(o.created_at))}${cell(badge(o.status))}${cell(`${esc(o.payment_method.toUpperCase())} · ${badge(o.payment_status)}`)}${cell(`${esc(o.pincode)}<br>${esc(o.delivery_date)}`)}${cell(money(o.grand_total))}${cell(action('order',o.id,'View order'))}</tr>`));
async function render(){
  if(!token)return;const version=++viewVersion;const content=$('#content');content.innerHTML='<p role="status">Loading workspace…</p>';
  document.querySelectorAll('[data-section]').forEach(button=>button.classList.toggle('active',button.dataset.section===section));
  try{
    let html='', data;
    if(section==='dashboard'){
      const [stats,alerts]=await Promise.all([api('/admin/dashboard'),api('/admin/alerts?page_size=1')]);
      html=`<div class="stats">${[['Orders today',stats.orders_today],['Ready to pack',stats.pending_pack],['Low-stock packs',stats.low_stock],['Unread alerts',alerts.unread]].map(([label,value])=>`<div class="panel stat"><span>${label}</span><strong>${value}</strong></div>`).join('')}</div><div class="panel"><div class="row"><h2>Latest orders</h2><span class="muted small">New activity checked every 15 seconds</span></div>${orderTable(stats.recent_orders)}</div><div class="panel"><h2>Start your day</h2><p>Check new orders, pack confirmed purchases, and record shipment details before dispatch. Online orders must show paid; COD orders show cash due.</p><p class="muted">Dashboard alerts work while this page is open. Email delivery status is available in Order alerts.</p><button data-action="notifications">Enable browser alerts</button></div>`;
    }else if(section==='orders'){
      data=await api('/admin/orders?'+query());records=data.items;
      html=`<form id="filters" class="toolbar"><input name="order_number" aria-label="Order number" placeholder="Search order number" value="${esc(filter.order_number)}"><select name="status" aria-label="Order status">${['','pending_payment','confirmed','packed','shipped','delivered','cancelled'].map(v=>`<option value="${v}" ${filter.status===v?'selected':''}>${v?v.replaceAll('_',' '):'All statuses'}</option>`).join('')}</select><input type="date" name="date_from" aria-label="From date" value="${esc(filter.date_from)}"><input type="date" name="date_to" aria-label="To date" value="${esc(filter.date_to)}"><button>Apply filters</button><button type="button" data-action="export-orders">Export filtered orders</button></form><div class="panel">${orderTable(records)}${pager(data)}</div>`;
    }else if(section==='inventory'){
      data=await api('/admin/inventory?'+query());records=data.items;
      html=`<div class="notice">Available stock excludes quantities reserved by unpaid orders. Enter the quantity you can sell now.</div><div class="panel">${table(['SKU','Pack','Available','Price',''],records.map(v=>`<tr>${cell(esc(v.sku))}${cell(esc(v.pack_label))}${cell(badge(v.stock_qty<=5?'low stock':String(v.stock_qty))+' '+(v.stock_qty<=5?v.stock_qty:''))}${cell(money(v.price))}${cell(action('stock',v.id,'Update stock'))}</tr>`))}${pager(data)}</div>`;
    }else if(section==='alerts'){
      data=await api('/admin/alerts?'+query());records=data.items;
      html=`<div class="notice">${data.unread} unread. “Sent” means the email provider accepted the message; inbox delivery can still depend on your email provider. Unsent alerts stay saved for retry.</div><div class="panel">${table(['Event','Order','Time (IST)','Email','Read',''],records.map(a=>`<tr>${cell(esc(a.kind.replaceAll('_',' ')))}${cell(action('order',a.order_id,a.order_number))}${cell(date(a.created_at))}${cell(a.sent_at?badge('sent'):a.last_error?badge('failed')+'<br>'+esc(a.last_error):badge('queued'),true)}${cell(a.seen_at?'Read':action('read-alert',a.id,'Mark read'))}${cell(!a.sent_at&&actor.role==='admin'?action('retry-alert',a.id,'Retry email'):'')}</tr>`))}${pager(data)}</div>`;
    }else if(section==='products'){
      data=await api('/admin/products?'+query());records=data.items;
      html=`<form id="filters" class="toolbar"><input name="search" aria-label="Search products" placeholder="Product name or SKU" value="${esc(filter.search)}"><button>Search</button><button type="button" class="primary" data-action="product">Add product</button></form><div class="panel">${table(['Product','Category','Packs','Visibility',''],records.map(p=>`<tr>${cell(`<strong>${esc(p.name)}</strong><div class="muted small">${esc(p.origin)}</div>`,true)}${cell(esc(p.category.replaceAll('_',' ')))}${cell(p.variants.length)}${cell(badge(p.is_active?'published':'draft'))}${cell(action('product',p.id,'Edit product'))}</tr>`))}${pager(data)}</div>`;
    }else if(section==='delivery'){
      data=await api('/admin/pincodes?'+query());records=data.items;
      html=`<div class="notice">Enable delivery only after your courier or delivery team confirms the area. Postal-directory entries do not activate delivery.</div><form id="filters" class="toolbar"><input name="search" aria-label="Search coverage" placeholder="Pincode, city or state" value="${esc(filter.search)}"><button>Search</button><button type="button" class="primary" data-action="coverage">Add delivery area</button><button type="button" data-action="import-coverage">Import coverage CSV</button><button type="button" data-action="coverage-template">Download CSV template</button></form><div class="panel">${table(['Pincode','City / state','Delivery','Fresh fruit','Days','COD',''],records.map(p=>`<tr>${cell(esc(p.pincode))}${cell(`${esc(p.city)}<br><span class="muted">${esc(p.state)}</span>`,true)}${cell(badge(p.serviceable?'enabled':'disabled'))}${cell(p.mango_eligible?'Eligible':'No')}${cell(`${p.delivery_days_min}–${p.delivery_days_max}`)}${cell(p.cod_allowed?'Yes':'No')}${cell(action('coverage',p.pincode,'Edit'))}</tr>`))}${pager(data)}</div>`;
    }else if(section==='postal'){
      data=await api('/admin/postal-directory?'+query());records=data.items;
      html=`<div class="notice">Reference data by <a href="https://www.geonames.org/" target="_blank" rel="noopener noreferrer">GeoNames</a>. Search post offices and towns, then add verified areas under Delivery areas. ${data.total===0?'No postal references match this search.':''}</div><form id="filters" class="toolbar"><input name="search" aria-label="Search postal directory" placeholder="Pincode, town, district or state" value="${esc(filter.search)}"><button>Search</button></form><div class="panel">${table(['Pincode','District','State','Post offices',''],records.map(p=>`<tr>${cell(esc(p.pincode))}${cell(esc(p.district))}${cell(esc(p.state))}${cell(esc(p.offices.join(', ')),true)}${cell(action('postal-coverage',p.pincode,'Set coverage'))}</tr>`))}${pager(data)}</div>`;
    }else if(section==='banners'||section==='seasons'){
      data=await api(section==='banners'?'/admin/banners':'/admin/mango-seasons');records=data.items;
      html=`<div class="toolbar"><button class="primary" data-action="${section==='banners'?'banner':'season'}">Add ${section==='banners'?'offer':'season'}</button></div><div class="panel">${table(['Name','Starts','Ends','Status',''],records.map(r=>`<tr>${cell(esc(r.title||r.variety_name),true)}${cell(esc(r.start_date||r.harvest_start))}${cell(esc(r.end_date||r.harvest_end))}${cell(badge(section==='banners'?(r.is_published?'published':'draft'):r.status))}${cell(action(section==='banners'?'banner':'season',r.id,'Edit'))}</tr>`))}</div>`;
    }else if(section==='refunds'){
      data=await api('/admin/refunds?'+query());records=data.items;
      html=`<div class="notice">Cancelled paid orders create a refund request. Processing submits queued refunds through the configured payment gateway.</div><button data-action="refunds">Process queued refunds</button><div class="panel">${table(['Order','Amount','Status','Gateway reference','Issue'],records.map(r=>`<tr>${cell(action('order',r.order_id,'View order'))}${cell(money(r.amount))}${cell(badge(r.status))}${cell(esc(r.gateway_ref||'—'))}${cell(esc(r.last_error||'—'),true)}</tr>`))}${pager(data)}</div>`;
    }else if(section==='settings'){
      data=await api('/admin/settings');const v=data.values,r=data.readiness;
      html=`<div class="two"><form id="settings-form" class="panel"><h2>Business details</h2>${input('business_name','Business name',v.business_name,'text',false)}${input('business_address','Business / dispatch address',v.business_address,'text',false)}${input('support_email','Customer support email',v.support_email,'email',false)}${input('support_phone','Support phone (optional)',v.support_phone,'tel',false)}${input('gstin','GSTIN (if applicable)',v.gstin,'text',false)}<h2>Owner emails</h2>${input('owner_email','New-order alert email',v.owner_email,'email',false)}${check('email_alerts_enabled','Send new-order and cancellation emails',v.email_alerts_enabled)}<h2>Ready to accept orders?</h2>${check('catalog_reviewed','I verified the products, prices and available stock',v.catalog_reviewed)}${check('coverage_reviewed','My delivery team confirmed the enabled pincodes',v.coverage_reviewed)}${check('policies_reviewed','Business policies and delivery charges are correct',v.policies_reviewed)}${check('orders_enabled','Accept customer orders',r.orders_enabled)}<button class="primary">Save business settings</button><p id="settings-error" role="alert"></p></form><div><div class="panel"><h2>Setup status</h2><ul class="checklist">${[['Business details','business'],['Approved delivery areas','delivery'],['Catalog reviewed','catalog'],['Policies reviewed','policies'],['Owner email service','owner_email'],['Online payment configuration','online_payments']].map(([label,key])=>`<li><span>${label}</span>${badge(r[key]?'ready':'pending')}</li>`).join('')}</ul><p>Payment mode: ${badge(r.payment_mode)}</p><p class="muted">Live online payments are deferred until your merchant account is activated. COD uses product and area eligibility.</p></div><div class="panel"><h2>Provider setup</h2><p>Keep payment and email secrets in Render environment settings. They are never displayed in this dashboard.</p><p class="small">Payment callback: <code>/api/v1/payments/callback</code><br>Signed webhook: <code>/api/v1/payments/gateway-webhook</code></p><p class="muted">Email jobs retry while the service is active. An always-on worker is needed for guaranteed unattended dispatch when free hosting sleeps.</p></div></div></div>`;
    }else if(section==='staff'){
      data=await api('/admin/staff');records=data.items;
      html=`<div class="toolbar"><button class="primary" data-action="staff">Add team member</button></div><div class="panel">${table(['Name','Email','Role','Status',''],records.map(s=>`<tr>${cell(esc(s.name))}${cell(esc(s.email))}${cell(esc(s.role))}${cell(badge(s.is_active?'active':'disabled'))}${cell(action('staff',s.id,'Edit access'))}</tr>`))}</div>`;
    }else if(section==='audit'){
      data=await api('/admin/audit?'+query());records=data.items;
      html=`<div class="panel">${table(['Time (IST)','Staff ID','Action','Resource'],records.map(r=>`<tr>${cell(date(r.created_at))}${cell(esc(r.admin_id),true)}${cell(esc(r.method))}${cell(esc(r.path),true)}</tr>`))}${pager(data)}</div>`;
    }
    if(version!==viewVersion||!token)return;
    content.innerHTML=`<header class="pagehead"><div><h1>${sections[section]}</h1><div class="muted">Grove & Stone operations</div></div><button id="refresh">Refresh</button></header>${html}`;
    $('#refresh').onclick=render;
    content.querySelectorAll('[data-page]').forEach(button=>button.onclick=()=>{page+=Number(button.dataset.page);render();});
    if($('#filters'))$('#filters').onsubmit=event=>{event.preventDefault();filter=formData(event.target);page=1;render();};
    if($('#settings-form'))$('#settings-form').onsubmit=async event=>{event.preventDefault();event.submitter.disabled=true;try{await api('/admin/settings','PATCH',formData(event.target));toast('Business settings saved');await render();}catch(error){$('#settings-error').textContent=error.message;event.submitter.disabled=false;}};
  }catch(error){if(version===viewVersion&&token){content.innerHTML=`<div class="panel"><h1>Could not load this section</h1><p role="alert">${esc(error.message)}</p><button id="retry-view">Try again</button></div>`;$('#retry-view').onclick=render;}}
}
async function all(path){let items=[],next=1;while(true){const data=await api(path+(path.includes('?')?'&':'?')+'page_size=50&page='+next++);items.push(...data.items);if(!data.total||items.length>=data.total)return items;}}
function download(name,rows){const csv=rows.map(row=>row.map(value=>'"'+String(value??'').replace(/^[=+@\-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function orderEditor(id){
  const o=await api('/admin/orders/'+id);const next={confirmed:'packed',packed:'shipped',shipped:'delivered'}[o.status];
  editor(o.order_number,`<div class="row"><p>${badge(o.status)} ${badge(o.payment_status)} · ${esc(o.payment_method.toUpperCase())}</p><button type="button" data-action="print">Print packing slip</button></div><div class="two"><div><h3>Deliver to</h3><pre>${esc([o.address.full_name,o.address.phone,o.address.line1,o.address.line2,o.address.landmark,o.address.city,o.address.state,o.pincode].filter(Boolean).join('\n'))}</pre></div><div><h3>Order details</h3><p>Placed: ${date(o.created_at)}<br>Delivery date: ${esc(o.delivery_date)}</p><p>${esc(o.customer_notes||'No delivery notes')}</p></div></div>${table(['Product / SKU','Pack','Qty','Total'],o.lines.map(l=>`<tr>${cell(`${esc(l.product_name)}<br><span class="muted">${esc(l.sku)}</span>`,true)}${cell(esc(l.variant_label))}${cell(l.qty)}${cell(money(l.line_total))}</tr>`))}<dl><dt>Subtotal</dt><dd>${money(o.subtotal)}</dd><dt>Included GST</dt><dd>${money(o.gst)}</dd><dt>Delivery</dt><dd>${money(o.shipping)}</dd><dt>Total</dt><dd><strong>${money(o.grand_total)}</strong></dd></dl>${o.shipment?`<div class="notice">${esc(o.shipment.carrier)} · ${esc(o.shipment.tracking_number)}${o.shipment.tracking_url?`<br><a href="${esc(o.shipment.tracking_url)}" target="_blank" rel="noopener noreferrer">Track shipment</a>`:''}</div>`:''}<div class="toolbar">${next?action('advance-order',o.id,'Mark '+next):''}${o.status==='confirmed'?action('cancel-order',o.id,'Cancel order'):''}${['confirmed','packed','shipped'].includes(o.status)?action('shipment',o.id,'Shipment details'):''}${o.payment_method==='cod'&&o.status==='delivered'&&o.payment_status!=='paid'?action('collect-cod',o.id,'Record cash collected'):''}</div><p class="muted small">Packing slips are operational records, not GST tax invoices.</p>`,async()=>{});
  $('#editor-form footer button[type=submit]').hidden=true;
}
const originalEditor=editor;
editor=function(...args){$('#editor-form footer button[type=submit]').hidden=false;originalEditor(...args);};
function packForm(pack={},index=0){return `<fieldset class="pack" data-pack><legend>Pack ${index+1}</legend>${pack.id?`<input type="hidden" name="id" value="${esc(pack.id)}">`:''}<div class="fields">${input('sku','SKU',pack.sku)}${input('pack_label','Pack label',pack.pack_label)}${select('pack_type','Pack type',pack.pack_type||'weight',['weight','box','tin'])}${input('price','Price (GST inclusive)',pack.price,'number')}${input('weight_grams','Weight in grams',pack.weight_grams??'','number',false)}${input('unit_count','Piece count',pack.unit_count??'','number',false)}${input('gst_percent','GST %',pack.gst_percent??0,'number')}${input('stock_qty','Available stock',pack.stock_qty??0,'number')}${check('cod_allowed','Allow COD',pack.cod_allowed)}${check('is_default','Default pack',pack.is_default??index===0)}</div></fieldset>`;}
async function productEditor(id){
  const p=id?await api('/admin/products/'+id):{variants:[{}]};
  editor(id?'Edit product':'Add product',`<div id="product-fields" class="fields">${input('name','Product name',p.name)}${input('slug','URL name (e.g. green-kiwi)',p.slug)}${select('category','Category',p.category||'exotic',['exotic','dry_fruit','mango'])}${input('origin','Origin',p.origin)}${select('season_status','Season status',p.season_status||'in_season',['in_season','limited','coming_soon','off_season'])}${input('harvest_window','Harvest window',p.harvest_window,'text',false)}${textarea('short_description','Short description',p.short_description,true)}${textarea('long_description','Full description',p.long_description,true)}${textarea('images','Image URLs (one per line)',(p.images||[]).join('\n'),true)}${textarea('handling_notes','Storage and handling',p.handling_notes)}${textarea('ripeness_note','Ripeness note',p.ripeness_note)}${textarea('farm_story','Farm story',p.farm_story)}${check('is_active','Published in the shop',p.is_active)}${check('is_gift_eligible','Gift eligible',p.is_gift_eligible)}</div><h3>Product packs</h3><p class="muted small">Keep existing packs to preserve orders and reservations. Set exactly one default pack.</p><div id="packs">${p.variants.map(packForm).join('')}</div><button type="button" data-action="add-pack">Add another pack</button>`,async()=>{
    const fields={};$('#product-fields').querySelectorAll('[name]').forEach(el=>fields[el.name]=el.type==='checkbox'?el.checked:el.value);
    fields.images=fields.images.split('\n').map(v=>v.trim()).filter(Boolean);
    fields.variants=[...document.querySelectorAll('[data-pack]')].map(pack=>{const v={};pack.querySelectorAll('[name]').forEach(el=>v[el.name]=el.type==='checkbox'?el.checked:el.value);['stock_qty','weight_grams','unit_count'].forEach(key=>v[key]=v[key]===''?null:Number(v[key]));if(v.id&&v.stock_qty===p.variants.find(original=>original.id===v.id)?.stock_qty)delete v.stock_qty;return v;});
    await api('/admin/products'+(id?'/'+id:''),id?'PATCH':'POST',fields);
  });
}
function coverageEditor(p={}){editor(p.pincode?'Delivery area '+p.pincode:'Add delivery area',`<div class="fields">${input('pincode','Pincode',p.pincode)}${input('city','City / town',p.city)}${input('state','State / union territory',p.state)}${input('delivery_days_min','Minimum delivery days',p.delivery_days_min??1,'number')}${input('delivery_days_max','Maximum delivery days',p.delivery_days_max??3,'number')}</div>${check('serviceable','Delivery team confirmed this area is serviceable',p.serviceable)}${check('mango_eligible','Fresh fruit / mango delivery supported',p.mango_eligible)}${check('cod_allowed','Cash on delivery supported',p.cod_allowed)}`,async data=>{data.delivery_days_min=Number(data.delivery_days_min);data.delivery_days_max=Number(data.delivery_days_max);const existing=await api('/admin/pincodes?search='+encodeURIComponent(data.pincode));if(existing.items.some(row=>row.pincode===data.pincode)){const pin=data.pincode;delete data.pincode;await api('/admin/pincodes/'+pin,'PATCH',data);}else await api('/admin/pincodes','POST',data);});}
document.addEventListener('click',async event=>{
  const button=event.target.closest('[data-action]');if(!button||button.disabled)return;const {action:name,id}=button.dataset;button.disabled=true;
  try{
    if(name==='order')await orderEditor(id);
    else if(name==='product')await productEditor(id);
    else if(name==='add-pack')$('#packs').insertAdjacentHTML('beforeend',packForm({},document.querySelectorAll('[data-pack]').length));
    else if(name==='print')window.print();
    else if(name==='stock'){const v=records.find(v=>v.id===id);editor('Update '+v.sku,input('stock_qty','Available quantity',v.stock_qty,'number'),data=>api('/admin/inventory','PATCH',{items:[{variant_id:id,stock_qty:Number(data.stock_qty)}]}));}
    else if(name==='read-alert'){await api('/admin/alerts/'+id+'/read','POST',{});await render();await poll();}
    else if(name==='retry-alert'){await api('/admin/alerts/'+id+'/retry','POST',{});toast('Email queued for retry');await render();}
    else if(name==='notifications'){if(!('Notification'in window))toast('This browser does not support notifications. Dashboard alerts remain available.');else toast((await Notification.requestPermission())==='granted'?'Browser alerts enabled while this dashboard is open.':'Browser alerts were not enabled.');}
    else if(name==='coverage')coverageEditor(records.find(p=>p.pincode===id)||{});
    else if(name==='postal-coverage'){const p=records.find(p=>p.pincode===id);coverageEditor({pincode:p.pincode,city:p.offices[0]||p.district,state:p.state});}
    else if(name==='coverage-template')download('Grove-and-Stone-delivery-template.csv',[['pincode','city','state','serviceable','mango_eligible','delivery_days_min','delivery_days_max','cod_allowed']]);
    else if(name==='import-coverage')editor('Import approved delivery coverage',`<p>Choose a CSV with the template headers. Existing pincodes will be updated; other areas are preserved. Maximum 3,000 rows per import.</p><label>Coverage file<input id="coverage-file" type="file" accept=".csv,text/csv" required></label>${check('confirmed','I reviewed this file and my delivery team supports the enabled areas')}`,async data=>{if(!data.confirmed)throw new Error('Confirm delivery coverage before importing.');const file=$('#coverage-file').files[0];if(!file||file.size>800000)throw new Error('Choose a CSV smaller than 800 KB.');await api('/admin/pincodes/import','POST',{csv:await file.text()});});
    else if(name==='advance-order'||name==='cancel-order'){
      const o=await api('/admin/orders/'+id),status=name==='cancel-order'?'cancelled':{confirmed:'packed',packed:'shipped',shipped:'delivered'}[o.status];
      dialog.close();editor('Confirm order update',`<p>Set ${esc(o.order_number)} to <strong>${esc(status)}</strong>?</p>${status==='cancelled'?'<p>Reserved stock will be released. Paid online orders will be queued for a refund.</p>':''}`,()=>api('/admin/orders/'+id+'/status','POST',{status}));
    }else if(name==='shipment'){
      const o=await api('/admin/orders/'+id),s=o.shipment||{};dialog.close();editor('Shipment details',input('carrier','Courier or delivery team',s.carrier)+input('tracking_number','Tracking number / delivery reference',s.tracking_number)+input('tracking_url','HTTPS tracking link (optional)',s.tracking_url,'url',false),data=>api('/admin/orders/'+id+'/shipment','PUT',data));
    }else if(name==='collect-cod'){
      const o=await api('/admin/orders/'+id);dialog.close();editor('Record collected cash',`<p>Confirm that your delivery team collected ${money(o.grand_total)} for ${esc(o.order_number)}.</p>${input('amount','Amount received',o.grand_total,'number')}`,data=>api('/admin/orders/'+id+'/collect-cod','POST',{amount:Number(data.amount).toFixed(2)}));
    }else if(name==='staff'){
      const s=records.find(s=>s.id===id)||{};editor(id?'Edit team access':'Add team member',input('name','Name',s.name)+(id?`<p>${esc(s.email)}</p>`:input('email','Email','','email'))+input('password',id?'New password (leave blank to keep)':'Password (12+ characters)','','password',!id)+select('role','Role',s.role||'packer',['packer','admin'])+check('is_active','Active access',s.is_active??true),data=>{if(!data.password)delete data.password;return api('/admin/staff'+(id?'/'+id:''),id?'PATCH':'POST',data);});
    }else if(name==='banner'){
      const b=records.find(b=>b.id===id)||{};editor(id?'Edit home offer':'Add home offer',`<div class="fields">${input('title','Title',b.title)}${input('subtitle','Subtitle',b.subtitle,'text',false)}${input('cta_label','Button label',b.cta_label)}${input('cta_url','Shop route (e.g. /category/exotic)',b.cta_url)}${input('image','Image URL',b.image)}${select('season_state','Season',b.season_state||'live',['live','coming_soon','closed'])}${input('start_date','Start date',b.start_date,'date')}${input('end_date','End date',b.end_date,'date')}</div>${check('is_published','Published',b.is_published)}`,data=>api('/admin/banners'+(id?'/'+id:''),id?'PATCH':'POST',data));
    }else if(name==='season'){
      const s=records.find(s=>s.id===id)||{},products=await all('/admin/products?category=mango');editor(id?'Edit mango season':'Add mango season',`<div class="fields">${input('variety_name','Variety name',s.variety_name)}<label>Product<select name="product_id"><option value="">No linked product</option>${products.map(p=>`<option value="${p.id}" ${s.product_id===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label>${input('harvest_start','Harvest starts',s.harvest_start,'date')}${input('harvest_end','Harvest ends',s.harvest_end,'date')}${input('preorder_open','Preorder opens',s.preorder_open,'date',false)}${input('preorder_close','Preorder closes',s.preorder_close,'date',false)}${select('status','Status',s.status||'upcoming',['upcoming','live','closed'])}</div>${check('waitlist_enabled','Enable waitlist',s.waitlist_enabled)}`,data=>{['product_id','preorder_open','preorder_close'].forEach(k=>data[k]||=null);return api('/admin/mango-seasons'+(id?'/'+id:''),id?'PATCH':'POST',data);});
    }else if(name==='export-orders'){
      const rows=await all('/admin/orders?'+new URLSearchParams(filter));download('Grove-and-Stone-orders.csv',[['order_number','created_at','status','payment_method','payment_status','pincode','delivery_date','total'],...rows.map(o=>[o.order_number,o.created_at,o.status,o.payment_method,o.payment_status,o.pincode,o.delivery_date,o.grand_total])]);
    }else if(name==='refunds')editor('Process refund queue','<p>Submit all queued eligible refunds to the configured gateway? This may return money to customers.</p>',()=>api('/admin/refunds/process','POST',{}));
  }catch(error){toast(error.message);}finally{button.disabled=false;}
});
let invitation = new URLSearchParams(location.hash.slice(1)).get('invite');
if(invitation){
  history.replaceState(null,'','/admin/activate');
  root.innerHTML=`<main class="login"><form class="panel" id="activate"><div class="brand">grove & stone / owners</div><h1>Set your owner password</h1><p class="muted">This private invitation can be used once. Use a unique password with at least 12 characters.</p>${input('password','New password','','password')}${input('confirm','Confirm password','','password')}<p id="login-error" role="alert"></p><button class="primary">Activate owner account</button></form></main>`;
  $('#activate').onsubmit=async event=>{event.preventDefault();const data=formData(event.target);if(data.password!==data.confirm){$('#login-error').textContent='Passwords do not match.';return;}event.submitter.disabled=true;try{const result=await api('/admin/auth/activate','POST',{token:invitation,password:data.password});invitation=null;token=result.access_token;actor=result.admin;shell();await render();poll();timer=setInterval(poll,15000);}catch(error){$('#login-error').textContent=error.message;event.submitter.disabled=false;}};
}else login();
