"""Build versioned WebP assets and tiny Base64 previews; run with Pillow installed."""
import base64
import hashlib
import io
import json
from pathlib import Path

from PIL import Image

root = Path(__file__).resolve().parents[1]
catalog = root / 'mobile/assets/catalog'
target = catalog / 'optimized'
target.mkdir(exist_ok=True)
entries, stats = [], []
for source in sorted(catalog.glob('*.png')):
    image = Image.open(source).convert('RGB')
    image.thumbnail((768, 768), Image.Resampling.LANCZOS)
    payload = io.BytesIO()
    image.save(payload, format='WEBP', quality=78, method=6)
    data = payload.getvalue()
    name = f'{source.stem}.{hashlib.sha256(data).hexdigest()[:12]}.webp'
    (target / name).write_bytes(data)
    image.thumbnail((20, 20), Image.Resampling.LANCZOS)
    preview = io.BytesIO()
    image.save(preview, format='WEBP', quality=30)
    placeholder = 'data:image/webp;base64,' + base64.b64encode(preview.getvalue()).decode('ascii')
    entries.append(f"  {json.dumps('/api/v1/media/' + source.name)}: {{ source: require('../assets/catalog/optimized/{name}'), placeholder: {json.dumps(placeholder)} }},")
    stats.append(dict(image=source.name, original_bytes=source.stat().st_size, optimized_bytes=len(data)))
(root / 'mobile/src/catalogImages.ts').write_text('// Generated by tools/optimize_images.py. Keep API references stable.\nexport const catalogImages: Record<string, { source: number; placeholder: string }> = {\n' + '\n'.join(entries) + '\n};\n', encoding='utf-8')
(target / 'sizes.json').write_text(json.dumps(stats, indent=2) + '\n', encoding='utf-8')
before, after = sum(s['original_bytes'] for s in stats), sum(s['optimized_bytes'] for s in stats)
print(f'{len(stats)} images: {before:,} -> {after:,} bytes ({100 * (1 - after / before):.1f}% smaller)')
